baseURL = 'https://www.gajabjobs.com/'
languageCode = 'en-US'
title = 'GAJAB JOBS'
enableRobotsTXT = true
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
disableKinds = ["sitemap"]
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'  
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[sitemap]
  filename = "sitemap.xml"
  changefreq = "daily"
  priority = 0.5

[params]
description = "Stay updated with the latest government schemes, Sarkari Yojna news, and policy updates on Gajab Jobs."
googleAnalyticsID = "G-Q2CVFK9K8P"

paginate = 20
  logo = "logo/GajabJobs540x100.png"
  homelogo = "logo/logo-192x192.png"
  [outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "JSON"]
page = ["HTML"]
